### ISSUE TITLE
feat: bootstrap demo

### ISSUE THREAD

**Issue by tim-hm** [glimpse-protocol/zerojs-demo#1]
A demo page will be useful for several reasons:

- showing what our integration looks like from an end user's perspective
- showing what our integration looks like in code
- highlighting the difference between a prematch and a postmatch (ie showing render times etc)

For accessibility, i think we should avoid a complex project structure (ie don't use webpack, react, etc). As much as is possible lets stick with vanilla HTML, ES5 and CSS 🙏 

## tasks

- [x] setup repository
- [ ] ~~setup ci pipeline~~
- [x] setup demo on the existing webserver instance
- [x] setup dns records
- [x] setup caddy reverse proxy + cert
- [x] build demo page (see [figma design](https://www.figma.com/file/5LvrUB9UY8lggW4zoKjd3Q/Frontend-User-Interfaces?node-id=2602%3A5546))

@eddieyu1998 fyi / keen for any input from you as well 🙏

**Comment by tim-hm** [comment]
Demo is coming together nicely! A few bits to address please:

- [x] can we fold the information about how the ad was served into the ad itself (ie demand via prebid / sponsorship)
- [x] lets keep the two units stack and reduce the padding so they mostly fit onto the view port
- [x] remove carbon for now until we have actual metrics to show
- [x] lets break load times down into bar charts where we compare prebid vs zerojs "local load times" ... perhaps we ask the user to refresh the page if there's is not enough data?
- [x] lets use Roboto font

**Comment by mountEvarus** [comment]
@tim-hm do you want to use the roboto font? Or should we use poppins from our cdn instead

**Comment by tim-hm** [comment]
Go with whatever you think looks best!

**Comment by mountEvarus** [comment]
@tim-hm just moving on to the bar chart stuff now, were the sections on the chart. What were the 3 sections you suggested to display this morning?

**Comment by mountEvarus** [comment]
Todos tomorrow:

- [x] Improve styling so that bar charts fit onto page horizontally
- [x] Investigate & improve prematched GAM load time measurement

**Comment by tim-hm** [comment]
Could you also trim the vertical spacing? 

Let’s timebox this … maybe get as far as you can by lunch then let’s reorient to the backend?
